### ISSUE TITLE
base.js invalid checksum

### ISSUE THREAD

**Issue by MCrypto** [poolgold/z-nomp-bitcoin-gold#14]
i keep getting this error

> 2017-11-24 16:22:26 [Master]    [PoolSpawner] Fork 2 died, spawning replacement worker...
2017-11-24 16:22:26 [Pool]      [bitcoin gold] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
/home/mylin/Pools/znomp-btg/node_modules/bs58check/base.js:40
    if (!payload) throw new Error('Invalid checksum')
                  ^

>Error: Invalid checksum
    at Object.decode (/home/mylin/Pools/znomp-btg/node_modules/bs58check/base.js:40:25)
    at Object.fromBase58Check (/home/mylin/Pools/znomp-btg/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/home/mylin/Pools/znomp-btg/node_modules/stratum-pool/lib/transactions.js:75:42)
    at new BlockTemplate (/home/mylin/Pools/znomp-btg/node_modules/stratum-pool/lib/blockTemplate.js:36:35)
    at JobManager.processTemplate (/home/mylin/Pools/znomp-btg/node_modules/stratum-pool/lib/jobManager.js:141:32)
    at /home/mylin/Pools/znomp-btg/node_modules/stratum-pool/lib/pool.js:581:66
    at itemFinished (/home/mylin/Pools/znomp-btg/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/mylin/Pools/znomp-btg/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/mylin/Pools/znomp-btg/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/mylin/Pools/znomp-btg/node_modules/stratum-pool/lib/daemon.js:95:17)
2017-11-24 16:22:26 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
/home/mylin/Pools/znomp-btg/node_modules/bs58check/base.js:40
    if (!payload) throw new Error('Invalid checksum')
                  ^

**Comment by realwallpapers** [comment]
check this in btg.json pool config  

  "rewardRecipients": {
        "": 1.0
    },

**Comment by realwallpapers** [comment]
you need add address

**Comment by MCrypto** [comment]
thank you :)) all good now :))
