### ISSUE TITLE
log startup error 

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [poolgold/z-nomp-bitcoin-gold#17]
Hi when starting znomp-bitcoin-gold I get the following erreor and cant seem to resolve it can anyone help please. Many Thanks

z-nomp@0.0.4 start /home/jamie/z-nomp-bitcoin-gold
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

/home/jamie/z-nomp-bitcoin-gold/libs/logUtil.js:31
var logDir = conflog.logging.files.directory;
                             ^

TypeError: Cannot read property 'files' of undefined
    at Object.<anonymous> (/home/jamie/z-nomp-bitcoin-gold/libs/logUtil.js:31:30)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jamie/z-nomp-bitcoin-gold/init.js:11:18)
    at Module._compile (module.js:641:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! z-nomp@0.0.4 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the z-nomp@0.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jamie/.npm/_logs/2017-12-08T03_07_18_792Z-debug.log

**Comment by martin-key** [comment]
Never met this error.

**Comment by jamiejacksoncumbria** [comment]
Fixed this. Problem was a problem with config.json. I started again from fresh with the config and it fixed it.
