### ISSUE TITLE
NOAuth Password Issues when using password with Redis

### ISSUE THREAD

**Issue by DecentralizeCoding** [poolgold/z-nomp-bitcoin-gold#21]
Hi everyone,

I have been using this pool server flawlessly for a while now however I just moved over to a new redis provider and now I have to use a password to connect as opposed to running redis locally and using no password.

I checked the code and it seems to support a redis password.

Here is what I get when I add the password to the config.json file:

nomp@NOMP-test:~/z-nomp-bitcoin-gold$ sudo npm start

> z-nomp@0.0.4 start /home/nomp/z-nomp-bitcoin-gold
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2018-01-05 15:28:47 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-01-05 15:28:47 [Master]    [CLI] CLI listening on port 17117

events.js:136
      throw er; // Unhandled 'error' event
      ^
ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/home/nomp/z-nomp-bitcoin-gold/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/home/nomp/z-nomp-bitcoin-gold/node_modules/redis-parser/lib/parser.js:303:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! z-nomp@0.0.4 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the z-nomp@0.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

If anyone can point me in the right direction that would be great, I believe i have checked all of the libs and even compared to a plain nomp and unomp I configured for redis authenticaiton to work. I am using Redis 4.0.6

Many thanks in advance for any help!

**Comment by moonchallenge** [comment]
I have the same problem too. @DecentralizeCoding Have you solved the problem yet?

**Comment by theeddie** [comment]
update?

**Comment by racquemis** [comment]
See #25 
There is a missing auth lin in init.js
