### ISSUE TITLE
Error: Invalid checksum

### ISSUE THREAD

**Issue by bcmonster** [poolgold/z-nomp-bitcoin-gold#26]
2018-03-03 13:34:42 [Master]	[PoolSpawner] Fork 3 died, spawning replacement worker...
2018-03-03 13:34:44 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2018-03-03 13:34:44 [Pool]	[bitcoin gold] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
/home/bcmonster/z-nomp-bitcoin-gold/node_modules/bs58check/base.js:41
    if (!payload) throw new Error('Invalid checksum')
                  ^

Error: Invalid checksum
    at Object.decode (/home/bcmonster/z-nomp-bitcoin-gold/node_modules/bs58check/base.js:41:25)
    at Object.fromBase58Check (/home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/node_modules/bitcoinjs-lib-zcash/src/address.js:11:27)
    at Object.exports.createGeneration (/home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/transactions.js:75:42)
    at new BlockTemplate (/home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/blockTemplate.js:36:35)
    at JobManager.processTemplate (/home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/jobManager.js:144:32)
    at /home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/pool.js:581:66
    at itemFinished (/home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/bcmonster/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:95:17)
2018-03-03 13:34:44 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...

Andy Ideas?

**Comment by bcmonster** [comment]
NM it was wallet address issue... got it
