### ISSUE TITLE
Error: Expected property "1" of type Satoshi, got Number 125000000000269150

### ISSUE THREAD

**Issue by remrat** [poolgold/z-nomp-bitcoin-gold#7]
Running Bitcoin Gold wallet, with complete blockchain.

When I start up z-nomp, the following error is displayed. This error only started showing after 100% of the blockchain was downloaded.

z-nomp@0.0.4 start /root/z-nomp
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js
2017-11-15 14:56:11 [POSIX] [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-11-15 14:56:11 [Master] [CLI] CLI listening on port 17117
2017-11-15 14:56:11 [PPLNT] [bitcoin gold] TimeShare processing setup with redis (127.0.0.1:6379)
2017-11-15 14:56:11 [Master] [PoolSpawner] Spawned 1 pool(s) on 2 thread(s)
2017-11-15 14:56:12 [Website] [Server] Website started on 0.0.0.0:80
2017-11-15 14:56:12 [Payments] [bitcoin gold] minimum paymentInterval of 120 seconds recommended.
2017-11-15 14:56:12 [Payments] [bitcoin gold] bitcoin gold requireShielding: true
2017-11-15 14:56:12 [Payments] [bitcoin gold] bitcoin gold minConf: 10
2017-11-15 14:56:12 [Payments] [bitcoin gold] bitcoin gold payments txfee reserve: 0.0004
2017-11-15 14:56:12 [Payments] [bitcoin gold] bitcoin gold maxBlocksPerPayment: 3
2017-11-15 14:56:12 [Payments] [bitcoin gold] bitcoin gold PPLNT: false, time period: 0.51
2017-11-15 14:56:12 [Payments] [bitcoin gold] Error with payment processing daemon {"code":-32601,"message":"Method not found"}
2017-11-15 14:56:12 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2017-11-15 14:56:12 [Pool] [bitcoin gold] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2017-11-15 14:56:12 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2017-11-15 14:56:12 [Pool] [bitcoin gold] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2017-11-15 14:56:12 [Pool] [bitcoin gold] (Thread 1) No rewardRecipients have been setup which means no fees will be taken
2017-11-15 14:56:12 [Pool] [bitcoin gold] (Thread 2) No rewardRecipients have been setup which means no fees will be taken

/root/z-nomp/node_modules/typeforce/index.js:159
throw tfSubError(e, i)
^
Error: Expected property "1" of type Satoshi, got Number 125000000000248140
at tfSubError (/root/z-nomp/node_modules/typeforce/errors.js:93:9)
at /root/z-nomp/node_modules/typeforce/index.js:159:17
at Array.every ()
at _tuple (/root/z-nomp/node_modules/typeforce/index.js:155:20)
at typeforce (/root/z-nomp/node_modules/typeforce/index.js:196:9)
at Transaction.addOutput (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/transaction.js:268:3)
at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:118:12)
at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:588:66

/root/z-nomp/node_modules/typeforce/index.js:159
throw tfSubError(e, i)
^
Error: Expected property "1" of type Satoshi, got Number 125000000000248140
at tfSubError (/root/z-nomp/node_modules/typeforce/errors.js:93:9)
at /root/z-nomp/node_modules/typeforce/index.js:159:17
at Array.every ()
at _tuple (/root/z-nomp/node_modules/typeforce/index.js:155:20)
at typeforce (/root/z-nomp/node_modules/typeforce/index.js:196:9)
at Transaction.addOutput (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/transaction.js:268:3)
at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:118:12)
at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:588:66
2017-11-15 14:56:12 [Master] [PoolSpawner] Fork 0 died, spawning replacement worker...

**Comment by martin-key** [comment]
You have problem with parsing the block reward from getblocktemplate. 
Are you sure you are running the latest versions?

Which is your OS?

**Comment by remrat** [comment]
Running the latest version (as of 5 days ago)

OS: Ubuntu 16.04

**Comment by martin-key** [comment]
The last version of BTG is from 2 days ago.
Please update.

**Comment by remrat** [comment]
Updated...

2017-11-15 16:51:49 [Pool]      [bitcoin gold] (Thread 1) Share processing setup with redis (127.0.0.1:                                                                                      6379)
/root/z-nomp-bitcoin-gold/node_modules/bs58check/base.js:40
    if (!payload) throw new Error('Invalid checksum')
                  ^

Error: Invalid checksum
    at Object.decode (/root/z-nomp-bitcoin-gold/node_modules/bs58check/base.js:40:25)
    at Object.fromBase58Check (/root/z-nomp-bitcoin-gold/node_modules/bitcoinjs-lib-zcash/src/address.j                                                                                      s:8:27)
    at Object.exports.createGeneration (/root/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/transac                                                                                      tions.js:75:42)
    at new BlockTemplate (/root/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/blockTemplate.js:36:3                                                                                      5)
    at JobManager.processTemplate (/root/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/jobManager.j                                                                                      s:141:32)
    at /root/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/pool.js:581:66
    at itemFinished (/root/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:9                                                                                      5:17)
2017-11-15 16:51:49 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...

**Comment by remrat** [comment]
Ok, updated... Now I am receiving:

2017-11-15 17:50:32 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
2017-11-15 17:50:32 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2017-11-15 17:50:32 [Pool]      [bitcoin gold] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
/root/z-nomp-bitcoin-gold/node_modules/bs58check/base.js:40
    if (!payload) throw new Error('Invalid checksum')

**Comment by remrat** [comment]
Working correctly now.  Thank you for your help.

**Comment by martin-key** [comment]
No problem. 
Wish you all the best (:
